### ISSUE TITLE
Membuat halaman dosen

### ISSUE THREAD

**Issue by DaffanTS** [DaffanTS/-latihan-web-2022#1]
Buatkan halaman dosen. Yang dapat memperlihatkan nama dosen yang tertera.
Dimana dalamnya terdapat beberapa komponen berikut ini :

No Induk Dosen
Nama Dosen
Email
No Telepon
Mata Kuliah
Tahun Masuk

buatkan dalam tampilan sederhana saja, yang terpenting sudah bisa terhubung ke database MYSQL
Terimakasih

**Comment by Sriiindarti** [comment]
Tugasnya udah selesai Daffan

**Comment by DaffanTS** [comment]
OK nice terima kasih Sri
